### ISSUE TITLE
[NPC][Desolace] Nijel's Point Guard

### ISSUE THREAD

**Issue by djawl** [RealLushen/Harbringers-Bugtracker#199]
## What is the Bug? (Brief Overview)
Guard NPCs are hostile to Alliance players. 

## WoW Head Link to Quest, Item etc.
NPC(Hostile): https://www.wowhead.com/npc=51839/nijels-point-guard
NPC(Friendly): https://www.wowhead.com/npc=8151/nijels-point-guard

## Expected Behavior
Friendly guards

## Current Behavior
Unfriendly guards

## Steps to Reproduce

1. Go to Nijel's Point, Desolace
2. Get murdered

## Attach a Video Link or Screenshot
GIF: https://gyazo.com/f7d5953654996764cc464aced5625e29

**Comment by RealLushen** [comment]
Fixed, Camp got completely reworked
