### ISSUE TITLE
[Quest][Teldrassil] Nature's Reprisal

### ISSUE THREAD

**Issue by djawl** [RealLushen/Harbringers-Bugtracker#2]
WOWHEAD LINK: https://www.wowhead.com/quest=13946/natures-reprisal

WHAT IS SUPPOSE TO HAPPEN: You're meant to use the quest item [Ireroot Seeds](https://www.wowhead.com/item=46716/ireroot-seeds) to kill the NPCs [Shadow Sprite](https://www.wowhead.com/npc=2003/shadow-sprite), [Rascal Sprite](https://www.wowhead.com/npc=2002/rascal-sprite), [Dark Sprite](https://www.wowhead.com/npc=2004/dark-sprite) & [Vicious Grell](https://www.wowhead.com/npc=2005/vicious-grell) to get quest credit.

WHAT ACTUALLY HAPPENS: When you use the [Ireroot Seeds](https://www.wowhead.com/item=46716/ireroot-seeds) on the on the NPCs they get stunned for the duration of the debuff but they don't die and killing them doesn't count towards the quest credit. 

ADDITIONAL INFO/IMAGES/VIDEO: -

**Comment by Cillez** [comment]
Maybe this will work. I dont have a wod client so i cant test this myself so run it in world db then restart server and test :D gl

@RealLushen 

```sql
-- Nature's Reprisal (13946) quest script
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` = 13 AND `SourceEntry` = 65455;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(13, 1, 65455, 0, 0, 31, 0, 3, 2002, 0, 0, 0, '', 'Nature''s Fury can hit only Rascal Sprite'),
(13, 1, 65455, 0, 1, 31, 0, 3, 2003, 0, 0, 0, '', 'Nature''s Fury can hit only Shadow Sprite'),
(13, 1, 65455, 0, 2, 31, 0, 3, 2004, 0, 0, 0, '', 'Nature''s Fury can hit only Dark Sprite');
UPDATE `creature_template` SET `AIName` = "SmartAI", `ScriptName` = '' WHERE `entry` IN (2002, 2003, 2004);
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (2002, 2003, 2004);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(2002, 0, 0, 0, 8, 0, 100, 1, 65455, 0, 0, 0, 33, 34440, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Rascal Sprite - on spell hit (65455) - give quest credit (34440)'),
(2003, 0, 0, 0, 8, 0, 100, 1, 65455, 0, 0, 0, 33, 34440, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Shadow Sprite - on spell hit (65455) - give quest credit (34440)'),
(2004, 0, 0, 0, 8, 0, 100, 1, 65455, 0, 0, 0, 33, 34440, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Dark Sprite - on spell hit (65455) - give quest credit (34440)');
DELETE FROM `spell_linked_spell` WHERE `spell_trigger` IN (65455, -65462);
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES
(65455, 65462, 1, 'Nature''s Fury - root and shrink effect'),
(-65462, 65456, 0, 'Nature''s Fury - explode effect');

**Comment by RealLushen** [comment]
> Maybe this will work. I dont have a wod client so i cant test this myself so run it in world db then restart server and test :D gl
> 
> @RealLushen
> 
> ```sql
> -- Nature's Reprisal (13946) quest script
> DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` = 13 AND `SourceEntry` = 65455;
> INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
> (13, 1, 65455, 0, 0, 31, 0, 3, 2002, 0, 0, 0, '', 'Nature''s Fury can hit only Rascal Sprite'),
> (13, 1, 65455, 0, 1, 31, 0, 3, 2003, 0, 0, 0, '', 'Nature''s Fury can hit only Shadow Sprite'),
> (13, 1, 65455, 0, 2, 31, 0, 3, 2004, 0, 0, 0, '', 'Nature''s Fury can hit only Dark Sprite');
> UPDATE `creature_template` SET `AIName` = "SmartAI", `ScriptName` = '' WHERE `entry` IN (2002, 2003, 2004);
> DELETE FROM `smart_scripts` WHERE `entryorguid` IN (2002, 2003, 2004);
> INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
> (2002, 0, 0, 0, 8, 0, 100, 1, 65455, 0, 0, 0, 33, 34440, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Rascal Sprite - on spell hit (65455) - give quest credit (34440)'),
> (2003, 0, 0, 0, 8, 0, 100, 1, 65455, 0, 0, 0, 33, 34440, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Shadow Sprite - on spell hit (65455) - give quest credit (34440)'),
> (2004, 0, 0, 0, 8, 0, 100, 1, 65455, 0, 0, 0, 33, 34440, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Dark Sprite - on spell hit (65455) - give quest credit (34440)');
> DELETE FROM `spell_linked_spell` WHERE `spell_trigger` IN (65455, -65462);
> INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES
> (65455, 65462, 1, 'Nature''s Fury - root and shrink effect'),
> (-65462, 65456, 0, 'Nature''s Fury - explode effect');
> ```

Thanks a lot! Will test it after a restart! :)

**Comment by RealLushen** [comment]
Fix applied, needs test after next restart.

**Comment by djawl** [comment]
Re-Tested and confirmed is working now!

/close
