### ISSUE TITLE
[NPC][Dun Morogh] Worgen Rusher

### ISSUE THREAD

**Issue by djawl** [RealLushen/Harbringers-Bugtracker#25]
## What is the Bug? (Brief Overview)
There's a random level 13 elite worgen in Dun Morogh.

## WoW Head Link to Quest, Item etc.
https://www.wowhead.com/npc=45535/worgen-rusher

## Expected Behavior
No Elite worgen in Dun Morogh.

## Current Behavior
Surprise Elite worgen in Dun Morogh.

## Steps to Reproduce

1. Go to part of the map shown in the screenshot below
2. Get slaughtered (If you're an unaware level 11 dwarf hunter)

## Attach a Video Link or Screenshot
Spawn Point in Dun Morogh: https://gyazo.com/af5993360ba11c097d00e6535c8b650b
Proof that it shouldn't be there: https://gyazo.com/e57f55ae6d3423f56fb599de358975e1

**Comment by RealLushen** [comment]
Fixed & Tested.
