### ISSUE TITLE
[NPC][Blasted Lands] Surwich Warden

### ISSUE THREAD

**Issue by djawl** [RealLushen/Harbringers-Bugtracker#292]
## What is the Bug? (Brief Overview)
Guards are hostile to alliance players.

## WoW Head Link to Quest, Item etc.
NPC: https://www.wowhead.com/npc=51542/surwich-warden

## Expected Behavior
Friendly guard

## Current Behavior
Unfriendly Guard

## Steps to Reproduce

1. Go to Surwich, Blased Lands
2. Crazy murderous guards

## Attach a Video Link or Screenshot
GIF: https://gyazo.com/9a9b50c69155709f30c30dd172e10515

**Comment by RealLushen** [comment]
Completely Reworked the Zone and Guards are fixed
