### ISSUE TITLE
[Quest NPC][Tirisfal Glades] A Thorn in our Side

### ISSUE THREAD

**Issue by djawl** [RealLushen/Harbringers-Bugtracker#51]
## What is the Bug? (Brief Overview)
The [NPC](https://www.wowhead.com/npc=1662/captain-perrine) that drops the [item](https://www.wowhead.com/item=52077/urgent-scarlet-memorandum#objective-of) required for the [quest](https://www.wowhead.com/quest=24981/a-thorn-in-our-side) spawns under the ground, so unless you got a ranged ability you can't aggro him. 

## WoW Head Link to Quest, Item etc.
NPC: https://www.wowhead.com/npc=1662/captain-perrine

## Expected Behavior
Standing inside the broken tower.

## Current Behavior
Walking around under the ground where he's meant to stand.

## Steps to Reproduce

1. Go to the marked area on the map.
2. Go inside the tower.
3. See a nameplate but no NPC.

## Attach a Video Link or Screenshot
GIF: https://gyazo.com/f7caa9ef13708774534ed26ec9e39188

**Comment by RealLushen** [comment]
Fixed the Pathing and also the Quest Item
