### ISSUE TITLE
Class Paladins

### ISSUE THREAD

**Issue by Decimation96** [RealLushen/Harbringers-Bugtracker#6]
Holy power isn't working properly or showing.

**Comment by RealLushen** [comment]
Please describe this issue better. For me and my tests Holy Power worked fine.

**Comment by Decimation96** [comment]
Well, for me, holy power wasn't showing up to endicate that I had holy power at all, but perhaps a visual because I was able to cast word of glory, but unable to cast [Seraphim]

**Comment by djawl** [comment]
Works fine on my unboosted pally:
https://gyazo.com/773ac1d67a15a391c57db03e2b9fce71
