### ISSUE TITLE
[Quest][Darkshore] Threat from the Water

### ISSUE THREAD

**Issue by BrandoFlakes09** [RealLushen/Harbringers-Bugtracker#96]
## What is the Bug? (Brief Overview)
Vile Spray not spawning from Vile Terrors being killed.  However down the road there are barely enough Vile Spray to kill for quest completion.
## WoW Head Link to Quest, Item etc.
https://www.wowhead.com/quest=13522/threat-from-the-water
https://www.wowhead.com/npc=33864/vile-terror
## Expected Behavior
Killing the Vile Terror's with the guards will spawn 3-5 Vile Sprays.

## Current Behavior
Vile Terror's are not spawning vile sprays instead they spawn separate and the Vile Sprays are being killed by the guards before you get a chance to attack.

## Steps to Reproduce

1. Accept "Threat from the Water"
2. Run to PoI
3. Kill Vile Terror
4. Witness no Vile Spray

## Attach a Video Link or Screenshot
(Killed at the exact same time look at the in game watch)
![WoWScrnShot_051322_121801](https://user-images.githubusercontent.com/105388656/168325290-e6c47107-6b5d-46e5-92e5-c7564f3a42ce.jpg)
![WoWScrnShot_051322_121802](https://user-images.githubusercontent.com/105388656/168325297-8fe04434-8e32-4894-b96b-747449de6d9c.jpg)

**Comment by djawl** [comment]
This quest does work as stated in the start of the post there's multiple quest credit NPCs spawned that you can kill to finish the quest. 

/Close
